core/urls.py
from django.urls import path

from .views import *

app_name = 'core'
urlpatterns = [
    path('',
         HomeView.as_view(),
         name='home'),
    path('research/',
         ResearchView.as_view(),
         name='research'),
    path('substitute/<int:id>',
         SubstituteView.as_view(),
         name='substitute'),
    path('product/<int:id>',
         ProductView.as_view(),
         name='product'),
    path('favorite',
         FavoriteFoodView.as_view(),
         name='favorite'),
    path('legal-notice',
         LegalNoticeView.as_view(),
         name='legal_notice'),
    path('contact',
         ContactView.as_view(),
         name='contact')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Categories(models.Model):
    name = models.CharField(max_length=500, unique=True)
    product_count = models.IntegerField(default=0)
    url = models.URLField()
    off_id = models.TextField()


class Food(models.Model):
    name = models.CharField(max_length=500, unique=True)
    brand = models.CharField(max_length=250)
    nutriscore = models.CharField(max_length=1)
    fat = models.FloatField(null=True)
    saturated_fat = models.FloatField(null=True)
    sugars = models.FloatField(null=True)
    salt = models.FloatField(null=True)
    url = models.URLField(unique=True)
    image_url = models.URLField(unique=True,
                                default="https://upload.wikimedia.org/wikipedia/commons/c/c5/Foods.jpg")
    categories = models.ManyToManyField('Categories')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_foods = models.ManyToManyField(Food)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

core/forms.py
from django import forms
from .models import Categories


class FoodRequestForm(forms.Form):
    food = forms.CharField(max_length=500,
                           widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Produit',
                                          'aria-label': 'Produit'}
                           ))


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ('name', 'product_count', 'url', 'off_id')

core/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator

from .models import Food
from .forms import FoodRequestForm


class HomeView(View):
    """Return the home template to the user and pass the
    food request form for the research bar in the template"""
    form = FoodRequestForm
    template_name = "core/home.html"

    def get(self, request):
        form = self.form
        context_dict = {'form': form}
        return render(request, self.template_name, context_dict)


class ResearchView(View):
    """Return results from a food research in the db with a 2d list format,
    or no context dict if there is no results"""
    form = FoodRequestForm
    template_name = "core/research.html"

    def get(self, request):
        form = self.form(request.GET)
        page = request.GET.get('page')
        if form.is_valid():
            research = form.cleaned_data.get('food')
            queryset = Food.objects.filter(name__icontains=research)

            if queryset.count() <= 0:
                return render(request, self.template_name)
            else:
                new_queryset = []
                for list in self.chunks(queryset, 3):
                    new_queryset.append(list)

                paginator = Paginator(new_queryset, 10)
                foods = paginator.get_page(page)
                context_dict = {"queryset": foods}
                if request.user.is_authenticated:
                    foods = request.user.profile.favorite_foods.all()
                    context_dict['favorite_foods'] = foods

                return render(request, self.template_name, context_dict)

    @staticmethod
    def chunks(l, n):
        for i in range(0, len(l), n):
            yield l[i:i + n]


class SubstituteView(View):
    """Return a 2d list filled with food substitute by doing a db research
    where all the element with a lower nutrition grade are filtered and all
    the elements who doesn't share 5 categories or more with our research"""
    template_name = 'core/substitute.html'

    def get(self, request, id):
        page = request.GET.get('page')
        food = Food.objects.get(id=id)
        categories = food.categories.all().order_by('id')
        nutriscore_list = self.nutriscore_list(food.nutriscore)

        queryset = Food.objects.filter(categories=categories[0]).filter(
                nutriscore__in=nutriscore_list).exclude(id=id)

        for category in categories[1:5]:
            query = Food.objects.filter(categories=category).filter(
                    nutriscore__in=nutriscore_list).exclude(id=id)
            queryset = queryset.intersection(query)

        if queryset.count() == 0:
            return render(request, self.template_name)
        else:
            new_queryset = []
            for list in self.chunks(queryset, 3):
                new_queryset.append(list)

            paginator = Paginator(new_queryset, 10)
            foods = paginator.get_page(page)
            context_dict = {"queryset": foods,
                            "research": food}
            if request.user.is_authenticated:
                foods = request.user.profile.favorite_foods.all()
                context_dict['favorite_foods'] = foods
            return render(request, self.template_name, context_dict)

    @staticmethod
    def nutriscore_list(nutriscore):
        if nutriscore == 'A':
            return ['A']
        elif nutriscore == 'B':
            return ['A']
        elif nutriscore == 'C':
            return ['A', 'B']
        elif nutriscore == 'D':
            return ['A', 'B', 'C']
        elif nutriscore == 'E':
            return ['A', 'B', 'C', 'D']
        elif nutriscore == 'Z':
            return ['A', 'B', 'C', 'D', 'E']

    @staticmethod
    def chunks(l, n):
        for i in range(0, len(l), n):
            yield l[i:i + n]


class ProductView(View):
    """Return the template for a single product"""
    template_name = 'core/product.html'

    def get(self, request, id):
        food = Food.objects.get(id=id)

        context_dict = {'food': food}

        return render(request, self.template_name, context_dict)


class FavoriteFoodView(View):
    """Return a template filled with all the foods a user saved.
    Only works if user is logged in"""
    template_name = 'core/favorite.html'

    @method_decorator(login_required)
    def post(self, request):
        food_id = request.POST['food_id']
        user = request.user
        if user.profile.favorite_foods.filter(id=food_id).count() == 1:
            return JsonResponse({'status': 'allready_faved'})
        elif user.profile.favorite_foods.filter(id=food_id).count() == 0:
            user.profile.favorite_foods.add(food_id)
            return JsonResponse({'status': 'ok'})

    @method_decorator(login_required)
    def get(self, request):
        user = request.user
        page = request.GET.get('page')
        queryset = user.profile.favorite_foods.all()

        if queryset.count() == 0:
            return render(request, self.template_name)
        else:
            new_queryset = []
            for list in self.chunks(queryset, 3):
                new_queryset.append(list)

            paginator = Paginator(new_queryset, 10)
            foods = paginator.get_page(page)
            context_dict = {"queryset": foods}
            return render(request, self.template_name, context_dict)

    @staticmethod
    def chunks(l, n):
        for i in range(0, len(l), n):
            yield l[i:i + n]


class LegalNoticeView(View):
    """Return the legal notice template"""
    template_name = 'core/legal_notice.html'

    def get(self, request):
        return render(request, self.template_name)


class ContactView(View):
    """Redirect the user to the contact me section in the home page"""

    def get(self, request):
        return redirect(reverse('core:home') + '#contact')

templates/core/contact.html
{% extends 'base.html' %}

{% block title %} - Mentions Légales
{% endblock %}

{% block content %}
  <section class="page-section h-25 first_section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-auto">
          <h1 class="section_title text-center">Contact</h1>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/core/favorite.html
{% extends 'base.html' %}

{% block title %} - Mes Aliments
{% endblock %}

{% block content %}
  <section id="user_account_section_block_top" class="page-section h-25 first_section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <h1 class="section_title text-center">Mes Aliments</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section h-auto">
    <div class="container my-auto">
      {% if queryset %}
        {% for subset in queryset %}
          <div class="row">
            {% for food in subset %}
              <div class="col-lg-4 col-sm-12 justify-content-center">
                <div class="product_block mx-auto">
                  <a href="{% url 'core:product' id=food.id %}">
                    {% if food.nutriscore == 'A' %}
                      <div class="nutriscore rank rank_a">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'B' %}
                      <div class="nutriscore rank rank_b">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'C' %}
                      <div class="nutriscore rank rank_c">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'D' %}
                      <div class="nutriscore rank rank_d">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'E' %}
                      <div class="nutriscore rank rank_e">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'Z' %}
                      <div class="nutriscore rank rank_z">?</div>
                    {% endif %}
                    <img src="{{ food.image_url }}" alt="food_image" class="food_image">
                  </a>
                  <p class="text-center food_title">{{ food.name }} par {{ food.brand }}</p>
                </div>
              </div>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="pagination row justify-content-center my-5">
        <span class="step-links">
        {% if queryset.has_previous %}
          <a href="?food={{ request.GET.food }}&page=1">&laquo; Début</a>
          <a href="?food={{ request.GET.food }}&page={{ queryset.previous_page_number }}">précedente</a>
        {% endif %}
          <span class="current">
          Page {{ queryset.number }} de {{ queryset.paginator.num_pages }}.
        </span>
          {% if queryset.has_next %}
            <a href="?food={{ request.GET.food }}&page={{ queryset.next_page_number }}">suivante</a>
            <a href="?food={{ request.GET.food }}&page={{ queryset.paginator.num_pages }}">Fin &raquo;</a>
          {% endif %}
        </span>
        </div>
      {% else %}
        <div class="row justify-content-center">
          <div class="col-lg-4">
            <h2 class="text-center">Aucun aliment enregistré</h2>
          </div>
        </div>
      {% endif %}
    </div>
  </section>
{% endblock %}

templates/core/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} - Acceuil
{% endblock %}

{% block content %}
  <section id="user_account_section_block_top" class="page-section h-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h1 class="text-white">Du gras, oui, mais de qualité</h1>
        </div>
      </div>
      <br>
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white">Trouvez un produit de substitution pour ceux que vous consommez tout les jours</h2>
        </div>
      </div>
      <br>
      <div class="row justify-content-center">
        <form action="{% url 'core:research' %}" method="get" class="col-lg-6">
          <div class="input-group">
            {{ form.food }}
            <div class="input-group-append">
              <button class="btn btn-secondary" type="submit">Rechercher</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
  <section id="story_section" class="page-section h-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg text-center">
          <h2 class="text-white">Colette & Remy</h2>
        </div>
      </div>
      <hr class="divider">
      <div class="row justify-content-center">
        <p class="col-lg-auto text-white text-justify">
          Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy,
          que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
        </p>
      </div>
      <div class="row justify-content-center">
        <p class="col-lg-auto text-white text-justify">
          <strong>Colette Tatou: </strong>
          "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"
        </p>
      </div>
      <div class="row justify-content-center">
        <p class="col-lg-auto text-white text-justify">
          <strong>Remy: </strong>
          "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"
        </p>
      </div>
      <hr class="divider">
      <div class="row justify-content-around">
        <div class="col-lg-4">
          <div>
            <img class="portrait" src="{% static 'images/colette.jpg' %}" alt="Colette picture">
          </div>
          <h3 class="text-center text-white">Colette</h3>
        </div>
        <div class="col-lg-4">
          <div>
            <img class="portrait" src="{% static 'images/remy.jpg' %}" alt="Remy picture">
          </div>
          <h3 class="text-center text-white">Remy</h3>
        </div>
      </div>
    </div>
  </section>
  <section id="contact" class="page-section h-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez nous !</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Prêt à mieux manger ?</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+33 1 22 33 44 55</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@pur-beurre.com">contact@pur-beurre.com</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/core/legal_notice.html
{% extends 'base.html' %}

{% block title %} - Mentions Légales
{% endblock %}

{% block content %}
  <section class="page-section h-25 first_section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-auto">
          <h1 class="section_title text-center">Mentions Légales</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section h-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-auto">
          <ul>
            <li><b>Coordonées de l'hébergeur: </b><a href="https://www.heroku.com/home">Heroku</a></li>
            <li><b>Template Bootstrap par: </b><a href="https://startbootstrap.com/">Start Bootstrap</a></li>
            <li><b>Icones Font Awesome: </b><a href="https://fontawesome.com/">Font Awesome</a></li>
            <li><b>Photo par: </b><a href="https://unsplash.com/@olenka_kotyk">Olenka Kotyk</a></li>
            <li><b>Code source: </b><a href="https://github.com/Axel-V/OC-Projet-8-Pur-beurre">Github</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/core/product.html
{% extends 'base.html' %}

{% block title %} - {{ food.name }}
{% endblock %}

{% block content %}
  <section class="page-section food_section h-25"
          style="background-image: url({{ food.image_url }})">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h1 class="section_title">{{ food.name }}</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="h-auto my-5">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col-lg-4 text-center">
          {% if food.nutriscore == 'A' %}
            {% include 'svg/nutriscore-a.svg' %}
          {% elif food.nutriscore == 'B' %}
            {% include 'svg/nutriscore-b.svg' %}
          {% elif food.nutriscore == 'C' %}
            {% include 'svg/nutriscore-c.svg' %}
          {% elif food.nutriscore == 'D' %}
            {% include 'svg/nutriscore-d.svg' %}
          {% elif food.nutriscore == 'E' %}
            {% include 'svg/nutriscore-e.svg' %}
          {% elif food.nutriscore == 'Z' %}
            {% include 'svg/nutriscore-z.svg' %}
          {% endif %}
        </div>
        <div class="col-lg-4">
          <h2 class="text-center">Repères nutritionnels pour 100g:</h2>
          <ul class="list-group">
            {% if food.fat %}
              <li class="list-group-item">Matières grasses: {{ food.fat }}g</li>
            {% elif not food.fat %}
              <li class="list-group-item">Matières grasses: Non connu</li>
            {% endif %}
            {% if food.saturated_fat %}
              <li class="list-group-item">Matières grasses saturées: {{ food.saturated_fat }}g</li>
            {% elif not food.saturated_fat %}
              <li class="list-group-item">Matières grasses saturées: Non connu</li>
            {% endif %}
            {% if food.sugars %}
              <li class="list-group-item">Sucre: {{ food.sugars }}g</li>
            {% elif not food.sugars %}
              <li class="list-group-item">Sucres: Non connu</li>
            {% endif %}
            {% if food.salt %}
              <li class="list-group-item">Sel: {{ food.salt }}g</li>
            {% elif not food.salt %}
              <li class="list-group-item">Sel: Non connu</li>
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
          <a href="{{ food.url }}" class="btn btn-primary">Voir la fiche d'OpenFoodFacts</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/core/research.html
{% extends 'base.html' %}

{% block title %} - Recherche
{% endblock %}

{% block content %}
  <section class="page-section h-25 first_section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-auto">
          <h1 class="section_title text-center">{{ request.GET.food }}</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section h-auto">
    <div class="container my-auto">
      {% if queryset %}
        <h2 class="text-center my-5">Cliquez sur un aliments pour avoir une liste de substituts</h2>
        {% for subset in queryset %}
          <div class="row">
            {% for food in subset %}
              <div class="col-lg-4 col-sm-12 justify-content-center">
                <div class="product_block mx-auto">
                  <a href="{% url 'core:substitute' id=food.id %}">
                    {% if food.nutriscore == 'A' %}
                      <div class="nutriscore rank rank_a">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'B' %}
                      <div class="nutriscore rank rank_b">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'C' %}
                      <div class="nutriscore rank rank_c">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'D' %}
                      <div class="nutriscore rank rank_d">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'E' %}
                      <div class="nutriscore rank rank_e">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'Z' %}
                      <div class="nutriscore rank rank_z">?</div>
                    {% endif %}
                    <img src="{{ food.image_url }}" alt="food_image" class="food_image">
                  </a>
                  <p class="text-center food_title">{{ food.name }} par {{ food.brand }}</p>
                  {% if user.is_authenticated %}
                    <div class="save_button_placeholder"></div>
                    {% if food in favorite_foods %}
                      <div>
                        <button class="btn btn-success active save_button" disabled>
                          <i class="fas fa-check"></i> Sauvegardé
                        </button>
                      </div>
                    {% else %}
                      <form class="favorite_form save_button" action="{% url 'core:favorite' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="food_id" value="{{ food.id }}">
                        <button type="submit" class="btn btn-outline-dark">
                          <i class="fas fa-save"></i> Sauvegarder
                        </button>
                      </form>
                    {% endif %}
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        {% endfor %}

        <div class="pagination row justify-content-center my-5">
    <span class="step-links">
        {% if queryset.has_previous %}
          <a href="?food={{ request.GET.food }}&page=1">&laquo; Début</a>
          <a href="?food={{ request.GET.food }}&page={{ queryset.previous_page_number }}">précedente</a>
        {% endif %}

      <span class="current">
            Page {{ queryset.number }} de {{ queryset.paginator.num_pages }}.
        </span>

      {% if queryset.has_next %}
        <a href="?food={{ request.GET.food }}&page={{ queryset.next_page_number }}">suivante</a>
        <a href="?food={{ request.GET.food }}&page={{ queryset.paginator.num_pages }}">Fin &raquo;</a>
      {% endif %}
    </span>
        </div>
      {% else %}
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h1>Pas de résultats !</h1>
          </div>
        </div>
      {% endif %}
    </div>

  </section>
{% endblock %}

templates/core/substitute.html
{% extends 'base.html' %}

{% block title %} - Résultats
{% endblock %}

{% block content %}
  <section class="page-section h-25 first_section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-auto">
          <h1 class="section_title text-center">{{ research.name }}</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section h-auto">
    <div class="container my-auto">
      {% if queryset %}
        <h2 class="text-center my-5">Vous pouvez remplacer cet aliment par:</h2>
        {% for subset in queryset %}
          <div class="row">
            {% for food in subset %}
              <div class="col-lg-4 col-sm-12 justify-content-center">
                <div class="product_block mx-auto">
                  <a href="{% url 'core:product' id=food.id %}">
                    {% if food.nutriscore == 'A' %}
                      <div class="nutriscore rank rank_a">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'B' %}
                      <div class="nutriscore rank rank_b">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'C' %}
                      <div class="nutriscore rank rank_c">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'D' %}
                      <div class="nutriscore rank rank_d">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'E' %}
                      <div class="nutriscore rank rank_e">{{ food.nutriscore }}</div>
                    {% elif food.nutriscore == 'Z' %}
                      <div class="nutriscore rank rank_z">?</div>
                    {% endif %}
                    <img src="{{ food.image_url }}" alt="food_image" class="food_image">
                  </a>
                  <p class="text-center food_title">{{ food.name }} par {{ food.brand }}</p>
                  {% if user.is_authenticated %}
                    <div class="save_button_placeholder"></div>
                    {% if food in favorite_foods %}
                      <div>
                        <button class="btn btn-success active save_button" disabled>
                          <i class="fas fa-check"></i> Sauvegardé
                        </button>
                      </div>
                    {% else %}
                      <form class="favorite_form save_button" action="{% url 'core:favorite' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="food_id" value="{{ food.id }}">
                        <button type="submit" class="btn btn-outline-dark">
                          <i class="fas fa-save"></i> Sauvegarder
                        </button>
                      </form>
                    {% endif %}
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        {% endfor %}

        <div class="pagination row justify-content-center my-5">
      <span class="step-links">
        {% if queryset.has_previous %}
          <a href="?page=1">&laquo; Début</a>
          <a href="?page={{ queryset.previous_page_number }}">précedente</a>
        {% endif %}

        <span class="current">
            Page {{ queryset.number }} de {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
          <a href="?page={{ queryset.next_page_number }}">suivante</a>
          <a href="?page={{ queryset.paginator.num_pages }}">Fin &raquo;</a>
        {% endif %}
      </span>
        </div>
        </div>
      {% else %}
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h1>Pas de substituts connus pour cet aliment !</h1>
          </div>
        </div>
      {% endif %}
  </section>
{% endblock %}