core/urls.py
from django.urls import path

from .views import *

app_name = 'core'
urlpatterns = [
    path('',
         HomeView.as_view(),
         name='home'),
    path('research/',
         ResearchView.as_view(),
         name='research'),
    path('substitute/<int:id>',
         SubstituteView.as_view(),
         name='substitute'),
    path('product/<int:id>',
         ProductView.as_view(),
         name='product'),
    path('favorite',
         FavoriteFoodView.as_view(),
         name='favorite'),
    path('legal-notice',
         LegalNoticeView.as_view(),
         name='legal_notice'),
    path('contact',
         ContactView.as_view(),
         name='contact')
]

user/urls.py
from django.urls import path

from .views import *

app_name = 'user'
urlpatterns = [
    path('signup/',
         SignUpView.as_view(),
         name='signup'),
    path('login/',
         ConnectionView.as_view(),
         name='login'),
    path('logout/',
         DisconnectionView.as_view(),
         name='logout'),
    path('account/',
         AccountView.as_view(),
         name='account')
]

core/forms.py
from django import forms
from .models import Categories


class FoodRequestForm(forms.Form):
    food = forms.CharField(max_length=500,
                           widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Produit',
                                          'aria-label': 'Produit'}
                           ))


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ('name', 'product_count', 'url', 'off_id')

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Pur beurre
    {% block title %}
    {% endblock %}
  </title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico'  %}" />
  <!-- font awesome icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=merriweather+sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <!-- plugin css -->
  <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
  <!-- theme css - includes bootstrap -->
  <link href="{% static 'css/creative.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<div id="wrap">
  <div id="main">
    <!-- Header / Navigation -->
    {% include 'navbar.html' %}
    <!-- Content -->
    {% block content %}
    {% endblock %}
  </div>
</div>

<!-- Footer -->
{% include 'footer.html' %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- Plugin JavaScript -->
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Custom scripts for this template -->
<script src="{% static 'js/creative.min.js' %}"></script>
<script src="{% static 'js/favorite.js' %}"></script>
</body>
</html>

templates/footer.html
{% load staticfiles %}

<footer class="bg-light footer py-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-auto text-center"><a href="{% url 'core:legal_notice' %}">Mentions Légales</a></div>
      <div class="col-auto text-center"><a href="{% url 'core:contact' %}">Contact</a></div>
    </div>
  </div>
</footer>

templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="{% url 'core:home' %}">
      <img id="logo_pur_beurre" class="d-inline-block" src="{% static 'images/logo_pur_beurre.png' %}" alt="logo pur beurre">Pur Beurre
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">

      <form class="form-inline ml-auto my-2 my-lg-0" action="{% url 'core:research' %}" method="get">
        <input type="text" name="food" class="form-control" placeholder="Rechercher" aria-label="rechercher" maxlength="500" required="" id="id_food" autocomplete="off">
      </form>

      <ul class="navbar-nav">

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:account' %}">
              {% include 'svg/user.svg' %} <div class="d-lg-none ml-2 d-inline">Mon compte</div>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'core:favorite' %}">
              {% include 'svg/carrot.svg' %} <div class="d-lg-none ml-2 d-inline">Mes aliments sauvegardés</div>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:logout' %}">
              {% include 'svg/sign-out.svg' %} <div class="d-lg-none ml-2 d-inline">Se déconnecter</div>
            </a>
          </li>

        {% else %}

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:login' %}">
              {% include 'svg/sign-in.svg' %} <div class="d-lg-none ml-2 d-inline">Se connecter</div>
            </a>
          </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>