core/urls.py
from django.urls import path

from .views import *

app_name = 'core'
urlpatterns = [
    path('',
         HomeView.as_view(),
         name='home'),
    path('research/',
         ResearchView.as_view(),
         name='research'),
    path('substitute/<int:id>',
         SubstituteView.as_view(),
         name='substitute'),
    path('product/<int:id>',
         ProductView.as_view(),
         name='product'),
    path('favorite',
         FavoriteFoodView.as_view(),
         name='favorite'),
    path('legal-notice',
         LegalNoticeView.as_view(),
         name='legal_notice'),
    path('contact',
         ContactView.as_view(),
         name='contact')
]

user/urls.py
from django.urls import path

from .views import *

app_name = 'user'
urlpatterns = [
    path('signup/',
         SignUpView.as_view(),
         name='signup'),
    path('login/',
         ConnectionView.as_view(),
         name='login'),
    path('logout/',
         DisconnectionView.as_view(),
         name='logout'),
    path('account/',
         AccountView.as_view(),
         name='account')
]

user/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, \
    AuthenticationForm, \
    UsernameField
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,
                                 required=False,
                                 help_text='Optionnel.',
                                 label='Prénom',
                                 widget=forms.TextInput(
                                         attrs={'class': 'form-control'}))

    last_name = forms.CharField(max_length=30,
                                required=False,
                                help_text='Optionnel.',
                                label='Nom',
                                widget=forms.TextInput(
                                        attrs={'class': 'form-control'}))

    email = forms.EmailField(max_length=254,
                             widget=forms.EmailInput(
                                     attrs={'class': 'form-control'}))

    password1 = forms.CharField(
            label=_("Password"),
            strip=False,
            help_text=password_validation.password_validators_help_text_html(),
            widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
            label=_("Password confirmation"),
            widget=forms.PasswordInput(attrs={'class': 'form-control'}),
            strip=False,
            help_text=_(
                    "Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = (
            'username', 'last_name', 'first_name', 'email', 'password1',
            'password2',)
        widgets = {'username': forms.TextInput(attrs={'class':
                                                          'form-control'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form-control'})
    )
    password = forms.CharField(
            label=_("Password"),
            strip=False,
            widget=forms.PasswordInput(attrs={
                'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ('username', 'password')

user/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from .forms import SignUpForm, LoginForm


class SignUpView(View):
    form = SignUpForm
    template_name = 'user/signup.html'

    def get(self, request):
        """Return the signup template"""
        form = self.form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """Process the signup form, redirect and log the user if it is
        valid, return the signup template otherwise"""
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('user:account')
        elif not form.is_valid():
            form = self.form(request.POST)
            return render(request, self.template_name, {'form': form})


class ConnectionView(LoginView):
    template_name = 'user/login.html'
    authentication_form = LoginForm


class DisconnectionView(LogoutView):

    def get(self, request, *args, **kwargs):
        return redirect('core:home')


class AccountView(View):
    template_name = 'user/account.html'

    @method_decorator(login_required)
    def get(self, request):
        user = request.user
        context_dict = {'user': user}
        return render(request, self.template_name, context_dict)

templates/user/account.html
{% extends 'base.html' %}

{% block title %} - Mon compte
{% endblock %}

{% block content %}
  <section id="user_account_section_block_top" class="page-section h-25">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          {% if user %}
          <h2 class="section_title text-center">{{ user.first_name }}</h2>
          {% else %}
          <h2 class="section_title text-center">{{ user.username }}</h2>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <section class="page-section h-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-black-50">{{ user.email }}</h2>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}
  - Connexion
{% endblock %}

{% block content %}
  <section class="page-section h-auto">
    <div class="container">
      <h2 class="text-center">Connexion</h2>
      <hr class="divider my-4">
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <div class="form-text text-muted">
                <small>{{ field.help_text }}</small>
              </div>
            {% endif %}
          </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Se connecter</button>
        <a href="{% url 'user:signup' %}">Nouveau ici ? S'enregistrer</a>
      </form>
      {% if form.errors %}
        <p>Votre nom d'utilisateur et le mot de passe ne correspondent pas</p>
      {% endif %}
    </div>
  </section>
{% endblock %}

templates/user/signup.html
{% extends 'base.html' %}

{% block title %}
  - Créer un compte
{% endblock %}

{% block content %}
  <section class="page-section h-auto">
    <div class="container">
      <h2 class="text-center">Créer un compte</h2>
      <hr class="divider my-4">
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <div class="form-text text-muted">
                <small>{{ field.help_text }}</small>
              </div>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Créer mon compte</button>
      </form>
    </div>
  </section>
{% endblock %}